apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  # Change this URI if you use MongoDB Atlas or an external cluster
  MONGO_URI: "mongodb://mongo-service:27017/campusDrive"
