apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-app
    project: node-k8s-app
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 80          # cluster-internal port
      targetPort: 3000  # container port (server.js listens here)
      nodePort: 30007   # access via http://<minikube-ip>:30007
